# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


# Runtime image for the GraalVM native build of the BFF. It only packages a binary built beforehand on a
# GraalVM 25 JDK, because compiling inside Docker needs ~9 GiB of memory:
#
#   ./gradlew -Pnative nativeCompile
#   docker compose -f compose.yaml -f compose.native.yaml up -d --build --wait
#
# The base image's glibc must be at least the build machine's (ubuntu-24.04 runners and this image: 2.39).
# Dockerfile.native.dockerignore limits the build context to build/native/nativeCompile.
FROM ubuntu:24.04
WORKDIR /app
COPY build/native/nativeCompile/ /app/
EXPOSE 8080
# Same sizing rule as the JVM image (heap is a share of the container limit), in native-image flag names.
ENTRYPOINT ["/app/consumer", "-XX:MaximumHeapSizePercent=60", "-XX:+ExitOnOutOfMemoryError"]
